# Generated by Django 5.0.1 on 2024-02-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_add_slug_to_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark a book as featured and show on home page slider'),
        ),
    ]
